- name: Create user
  user: name={{ user }}

- name: Get MD5 checksum of node-exporter executable
  stat:
    path: "/home/{{ user }}/{{ executable_name }}"
    checksum_algorithm: md5
  register: file_stat

- name: Detect arch
  command: uname -m
  check_mode: no
  register: arch

- name: Know if the directory exists
  stat:
    path: "/home/{{ user }}/{{ downloads[arch.stdout].directory }}"
  register: file_stat

- name: Download & extract node-exporter
  when: "file_stat.stat.exists == false"
  unarchive:
    src: "{{  downloads[arch.stdout].url }}"
    dest: "/home/{{ user }}"
    remote_src: yes
  register: download

- name: Set node-exporter ownership, group and permissions
  file:
    path: "/home/{{ user }}/{{ downloads[arch.stdout].directory }}/{{ executable_name }}"
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: "700"

- name: Remove unexpected files in home
  include_tasks: tasks/remove-unexpected-files.yml
  vars:
    directory: "/home/{{ user }}"
    files:
      - "{{ downloads[arch.stdout].directory }}"

- name: Render systemd service config
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  register: systemd

- name: Reload daemon
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Restart systemd app service
  systemd:
    name: node_exporter.service
    state: restarted
    enabled: yes
  when: systemd.changed or download.changed
