dependencies:
  - role: certbot
    vars:
      certbot_domain: "{{ frontman_domain }}"
      certbot_service_name: "frontman-certbot"
      certbot_email: "{{ frontman_certbot_email }}"
      certbot_post_hook: "cp {{ frontman_letsencrypt_ssl_cert_path }} {{ frontman_ssl_cert_path }} && cp {{ frontman_letsencrypt_ssl_key_path }} {{ frontman_ssl_key_path }} && systemctl restart frontman"
  - role: nginx
