- name: Ensure required variables are defined
  assert:
    that:
      - shadowsocks_gateway_server_uuid is string

- name: Ensure shadowsocks_gateway_users is defined correctly
  include_tasks: tasks/assert-users.yml
  vars:
    users: "{{ shadowsocks_gateway_users }}"

- name: Ensure shadowsocks_gateway_server is defined correctly
  include_tasks: tasks/assert-server.yml
  vars:
    server: "{{ shadowsocks_gateway_server }}"

- name: Install libnginx-mod-stream
  package:
    name: libnginx-mod-stream
    state: present

- name: Create user
  user: name={{ shadowsocks_gateway_user }}

- name: Render nginx config
  template:
    src: nginx.conf.j2
    dest: "/home/{{ shadowsocks_gateway_user }}/nginx.conf"
    group: "{{ shadowsocks_gateway_user }}"
    owner: "{{ shadowsocks_gateway_user }}"
    mode: "600"
  register: config

- name: Copy SSL key
  copy:
    content: "{{ shadowsocks_gateway_server.prometheus_metrics.tls.key }}"
    dest: "{{ shadowsocks_gateway_key_path }}"
    group: "{{ shadowsocks_gateway_user }}"
    owner: "{{ shadowsocks_gateway_user }}"
    mode: "600"
  register: ssl_key

- name: Copy SSL certificate
  copy:
    content: "{{ shadowsocks_gateway_server.prometheus_metrics.tls.certificate }}"
    dest: "{{ shadowsocks_gateway_certificate_path }}"
    group: "{{ shadowsocks_gateway_user }}"
    owner: "{{ shadowsocks_gateway_user }}"
    mode: "600"
  register: ssl_cert

- name: Remove unexpected files in home
  include_tasks: tasks/remove-unexpected-files.yml
  vars:
    directory: "/home/{{ shadowsocks_gateway_user }}"
    files:
      - nginx.conf
      - "{{ shadowsocks_gateway_certificate_filename }}"
      - "{{ shadowsocks_gateway_key_filename }}"
      - "{{ shadowsocks_gateway_pid_filename }}"
      - "{{ shadowsocks_gateway_nginx_conf_filename }}"
      - "{{ shadowsocks_gateway_http_access_log_filename }}"
      - "{{ shadowsocks_gateway_http_error_log_filename }}"
      - "{{ shadowsocks_gateway_tls_access_log_filename }}"
      - "{{ shadowsocks_gateway_tcp_error_log_filename }}"
      - "{{ shadowsocks_gateway_udp_error_log_filename }}"
      - "{{ shadowsocks_gateway_prometheus_access_log_filename }}"
      - "{{ shadowsocks_gateway_prometheus_error_log_filename }}"

- name: Render systemd service config
  template:
    src: shadowsocks-gateway.service.j2
    dest: /etc/systemd/system/shadowsocks-gateway.service
  register: systemd

- name: Reload daemon
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Restart systemd app service
  systemd:
    name: shadowsocks-gateway.service
    state: restarted
    enabled: yes
  when: systemd.changed or config.changed or ssl_key.changed or ssl_cert.changed
