repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
  - repo: local
    hooks:
      - id: file-does-not-exist-check
        name: Check if files do not exist
        language: script
        entry: .pre-commit-hooks/file-does-not-exist-check
        files: ^users.csv$
      - id: file-does-not-exist-check
        name: Check if files do not exist
        language: script
        entry: .pre-commit-hooks/file-does-not-exist-check
        files: ^id_rsa$
      - id: file-does-not-exist-check
        name: Check if files do not exist
        language: script
        entry: .pre-commit-hooks/file-does-not-exist-check
        files: ^id_rsa.pub$
      - id: file-is-empty-check
        name: Check if files are empty
        language: script
        entry: .pre-commit-hooks/file-is-empty-check
        files: ^vault.txt$
