repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
  - repo: local
    hooks:
      - id: ansible-vault-check
        name: Check if users.yml is encrypted with Ansible Vault
        language: script
        entry: .pre-commit-hooks/ansible-vault-check
        files: users.yml
      - id: ansible-vault-check
        name: Check if hosts is encrypted with Ansible Vault
        language: script
        entry: .pre-commit-hooks/ansible-vault-check
        files: hosts
      - id: file-does-not-exist-check
        name: Check if files do not exist
        language: script
        entry: .pre-commit-hooks/file-does-not-exist-check
        files: ^URIs.txt$
      - id: file-is-empty-check
        name: Check if files are empty
        language: script
        entry: .pre-commit-hooks/file-is-empty-check
        files: ^vault.txt$
