# linux user to run shadowsocks server as
shadowsocks_user: shadowsocks
# URL to download outline from
shadowsocks_downloads:
  x86_64:
    url: https://github.com/Jigsaw-Code/outline-ss-server/releases/download/v1.7.0/outline-ss-server_1.7.0_linux_x86_64.tar.gz
    md5: 40710b0e291fc8fa7eafbf5fbbf56035
  arm64:
    url: https://github.com/Jigsaw-Code/outline-ss-server/releases/download/v1.7.0/outline-ss-server_1.7.0_linux_arm64.tar.gz
    md5: 40710b0e291fc8fa7eafbf5fbbf56035
  armv7l:
    url: https://github.com/Jigsaw-Code/outline-ss-server/releases/download/v1.7.0/outline-ss-server_1.7.0_linux_armv7.tar.gz
    md5: 37cff757d1fbc2ad1e04e71aa4cdbec7
# name of outline executable file
shadowsocks_executable_name: outline-ss-server
# replay defense; see https://github.com/Jigsaw-Code/outline-ss-server/blob/master/service/PROBES.md for details
shadowsocks_replay_history: 10000
# port of metrics for prometheus to be exposed
shadowsocks_metrics_port: 9091
# port of shadowsocks behind gateway
shadowsocks_port: 46365
# shadowsocks listen address
shadowsocks_listen_address:
