- name: Ensure required variables are defined
  assert:
    that:
      - frontman_domain is string
      - frontman_port is number
      - frontman_certbot_email is string
      - frontman_default_redirect is string

- name: Ensure frontman_users is defined correctly
  include_tasks: tasks/assert-users.yml
  vars:
    users: "{{ frontman_users }}"

- name: Ensure frontman_servers is defined correctly
  include_tasks: tasks/assert-servers.yml
  vars:
    servers: "{{ frontman_servers }}"

- name: Install rsync
  package:
    name: rsync
    state: present

- name: Create user
  user: name={{ frontman_user }}

- set_fact:
    frontman_static_root_local: "/tmp/{{ frontman_static_directory_filename }}"
    frontman_instruction_filename: "{{ lookup('community.general.random_string', length=32, special=False) }}.html"

- set_fact:
    instruction_url: "https://{{ frontman_domain }}:{{ frontman_port }}/{{ frontman_instruction_filename }}"

- name: Create static directory locally
  delegate_to: localhost
  become: false
  file:
    path: "{{ frontman_static_root_local }}"
    state: directory

- name: Render index.html
  delegate_to: localhost
  become: false
  template:
    src: index.html.j2
    dest: "{{ frontman_static_root_local }}/index.html"

- name: Render guide.html
  delegate_to: localhost
  become: false
  copy:
    src: guide.html
    dest: "{{ frontman_static_root_local }}/{{ frontman_instruction_filename }}"

- name: Copy robots.txt
  delegate_to: localhost
  become: false
  copy:
    src: robots.txt
    dest: "{{ frontman_static_root_local }}/robots.txt"

- name: Render configs
  delegate_to: localhost
  become: false
  template:
    src: config.json.j2
    dest: "{{ frontman_static_root_local }}/{{ item.key }}"
  with_items: "{{ frontman_users | dict2items }}"
  loop_control:
    index_var: loop_index
  vars:
    frontman_user_uuid: "{{ item.key }}"
    frontman_default_server: "{{ (frontman_servers | dict2items)[loop_index % (frontman_servers | length)].value }}"
    frontman_default_server_uuid: "{{ (frontman_servers | dict2items)[loop_index % (frontman_servers | length)].key }}"

- name: Synchronize local static root with remote host
  synchronize:
    src: "{{ frontman_static_root_local }}"
    dest: "/home/{{ frontman_user }}"
    recursive: yes
    archive: no
    checksum: yes
    delete: yes

- name: Remove local static root
  delegate_to: localhost
  become: false
  file:
    path: "{{ frontman_static_root_local }}"
    state: absent

- name: Copy SSL key
  copy:
    src: "{{ frontman_letsencrypt_ssl_key_path }}"
    dest: "{{ frontman_ssl_key_path }}"
    group: "{{ frontman_user }}"
    owner: "{{ frontman_user }}"
    mode: "600"
    remote_src: yes
  register: ssl_private

- name: Copy SSL certificate
  copy:
    src: "{{ frontman_letsencrypt_ssl_cert_path }}"
    dest: "{{ frontman_ssl_cert_path }}"
    group: "{{ frontman_user }}"
    owner: "{{ frontman_user }}"
    mode: "600"
    remote_src: yes
  register: ssl_cert

- name: Remove unexpected files in home
  include_tasks: tasks/remove-unexpected-files.yml
  vars:
    directory: "/home/{{ frontman_user }}"
    files:
      - "{{ frontman_static_directory_filename }}"
      - "{{ frontman_ssl_cert_filename }}"
      - "{{ frontman_ssl_key_filename }}"
      - "{{ frontman_error_log_filename }}"
      - "{{ frontman_pid_filename }}"
      - "{{ frontman_nginx_conf_filename }}"

- name: Render nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ frontman_nginx_conf_path }}"
    group: "{{ frontman_user }}"
    owner: "{{ frontman_user }}"
    mode: "600"
  register: config

- name: Render systemd service config
  template:
    src: frontman.service.j2
    dest: /etc/systemd/system/frontman.service
  register: systemd

- name: Reload daemon
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Restart systemd app service
  systemd:
    name: frontman.service
    state: restarted
    enabled: yes
  when: systemd.changed or config.changed or ssl_private.changed or ssl_cert.changed
