- name: Load users
  delegate_to: localhost
  command: "curl -s {{ users_url }}"
  register: users_json

- name: Load users
  set_fact:
    users: "{{ users_json.stdout | from_json }}"

- name: Render users.csv
  become: false
  delegate_to: localhost
  template:
    src: users.csv.j2
    dest: "users.csv"
