- name: Install certbot
  package:
    name: certbot
    state: present

- name: Render systemd service config
  template:
    src: certbot.service.j2
    dest: /etc/systemd/system/{{ certbot_service_name }}.service
  register: systemd_service

- name: Render systemd timer config
  template:
    src: certbot.timer.j2
    dest: /etc/systemd/system/{{ certbot_service_name }}.timer
  register: systemd_timer

- name: Reload daemon
  systemd:
    daemon_reload: yes
  when: systemd_service.changed or systemd_timer.changed

- name: Enable systemd timer service
  systemd:
    name: "{{ certbot_service_name }}.timer"
    enabled: yes

- name: Run certbot one time
  systemd:
    name: "{{ certbot_service_name }}.service"
    state: restarted
