# linux user to run shadowsocks-gateway as
shadowsocks_gateway_user: shadowsocks-gateway
# where regular https requests (non-shadowsocks requests) proxy to
shadowsocks_gateway_fallback_proxy_target: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37333637313939636530653837626436396562306537353834326662383835353162393962336439
  6430373734363064656263373964363839643862326433660a383630663561313838666335343462
  65376263643234313439393933393262393932323664653030616432303439363164666539636362
  6139373831393530360a663130336433373266333635303637393735313932336131326162373734
  3066
# number of worker_connections in nginx
shadowsocks_gateway_worker_connections: 65536

shadowsocks_gateway_nginx_conf_filename: nginx.conf
shadowsocks_gateway_certificate_filename: cert.pem
shadowsocks_gateway_key_filename: key.pem
shadowsocks_gateway_error_log_filename: error.log
shadowsocks_gateway_pid_filename: nginx.pid

shadowsocks_gateway_nginx_conf_path: /home/{{ shadowsocks_gateway_user }}/{{shadowsocks_gateway_nginx_conf_filename }}
shadowsocks_gateway_certificate_path: "/home/{{ shadowsocks_gateway_user }}/{{ shadowsocks_gateway_certificate_filename }}"
shadowsocks_gateway_key_path: "/home/{{ shadowsocks_gateway_user }}/{{ shadowsocks_gateway_key_filename }}"
shadowsocks_gateway_error_log_path: "/home/{{ shadowsocks_gateway_user }}/{{ shadowsocks_gateway_error_log_filename }}"
shadowsocks_gateway_pid_path: "/home/{{ shadowsocks_gateway_user }}/{{ shadowsocks_gateway_pid_filename }}"
