# linus user to run prometheus as
prometheus_user: prometheus
# URL to download prometheus from
prometheus_downloads:
  x86_64:
    url: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-amd64.tar.gz
    directory: prometheus-2.46.0.linux-amd64
  arm64:
    url: https://github.com/prometheus/prometheus/releases/download/v2.46.0/prometheus-2.46.0.linux-arm64.tar.gz
    directory: prometheus-2.46.0.linux-arm64
  armv7l:
    url: https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-armv7.tar.gz
    directory: prometheus-2.47.2.linux-armv7
prometheus_executable_name: prometheus

prometheus_ssl_cert_filename: cert.pem
prometheus_ssl_key_filename: key.pem
prometheus_scrape_ssl_cert_filename_suffix: scrape_cert.pem
prometheus_scrape_ssl_certs_dir_name: certs

prometheus_ssl_cert_path: /home/{{ prometheus_user }}/{{ prometheus_ssl_cert_filename }}
prometheus_ssl_key_path: /home/{{ prometheus_user }}/{{ prometheus_ssl_key_filename }}
prometheus_scrape_ssl_cert_path: /home/{{ prometheus_user }}/{{ prometheus_scrape_ssl_cert_filename }}
