# linus user to run frontman as
frontman_user: frontman
# relative path of directory where static content should be stored
frontman_static_directory_filename: static
frontman_static_directory_path: /home/{{ frontman_user }}/{{ frontman_static_directory_filename }}

frontman_nginx_conf_filename: nginx.conf
frontman_ssl_cert_filename: cert.pem
frontman_ssl_key_filename: key.pem
frontman_error_log_filename: error.log
frontman_pid_filename: nginx.pid

frontman_nginx_conf_path: /home/{{ frontman_user }}/{{ frontman_nginx_conf_filename }}
frontman_ssl_cert_path: /home/{{ frontman_user }}/{{ frontman_ssl_cert_filename }}
frontman_ssl_key_path: /home/{{ frontman_user }}/{{ frontman_ssl_key_filename }}
frontman_error_log_path: /home/{{ frontman_user }}/{{ frontman_error_log_filename }}
frontman_pid_path: /home/{{ frontman_user }}/{{ frontman_pid_filename }}

frontman_letsencrypt_ssl_cert_path: "/etc/letsencrypt/live/{{ frontman_domain }}/fullchain.pem"
frontman_letsencrypt_ssl_key_path: "/etc/letsencrypt/live/{{ frontman_domain }}/privkey.pem"
