- name: Increase the maximum number of open file descriptors
  vars:
    limit: 51200
  block:
    - name: Set soft nofile limits for wildcard domain
      pam_limits:
        domain: '*'
        limit_type: soft
        limit_item: nofile
        value: "{{ limit }}"

    - name: Set hard nofile limits for wildcard domain
      pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: nofile
        value: "{{ limit }}"

- name: Tune the kernel parameters
  block:
    - sysctl:
        name: net.core.somaxconn
        value: '4096'
        state: present
    - sysctl:
        name: net.ipv4.tcp_keepalive_time
        value: '1200'
        state: present
    - sysctl:
        name: net.ipv4.ip_local_port_range
        value: '10000 65000'
        state: present
    - sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: '8192'
        state: present
    - sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: '5000'
        state: present
    - sysctl:
        name: net.ipv4.tcp_fastopen
        value: '3'
        state: present
    - sysctl:
        name: net.ipv4.tcp_mem
        value: '25600 51200 102400'
        state: present
    - sysctl:
        name: net.ipv4.tcp_rmem
        value: '4096 87380 67108864'
        state: present
    - sysctl:
        name: net.ipv4.tcp_wmem
        value: '4096 65536 67108864'
        state: present
    - sysctl:
        name: net.ipv4.tcp_mtu_probing
        value: '1'
        state: present
